### ISSUE TITLE
SWC Minifier 사용시 CSS가 적용되지 않음

### ISSUE THREAD

**Issue by HaJunRyu** [mash-up-kr/mash-up-recruit-fe#211]
![image](https://user-images.githubusercontent.com/71176945/210842414-de23c8e0-e014-451a-af40-2c0f682e51e3.png)
해당 이미지처럼 CSS가 아예 적용되지 않는 모습입니다.

**Comment by HaJunRyu** [comment]
SWC로 트랜스파일러 변경시 styledsheet에서 className에 파일명이 들어감, 하지만 파일명과 함께 확장자가 붙으며 그 사이에 존재하는 `.`이 그대로 className에 반영되고 CSS 선택자가 완전히 바뀌어버림
![image](https://user-images.githubusercontent.com/71176945/210842725-0c09d0a0-7e05-4b8f-b5a2-42b6227825d2.png)

Babel로 트랜스 파일링시 className에 파일명이 들어가도 확장자가 붙지 않기 때문에 `.`은 반영되지 않고 있음, 나머지는 하이픈으로 구분되어 CSS선택자에 지장 없음

**Comment by HaJunRyu** [comment]
## 원인
```javascript
compiler: {
    emotion: {
      autoLabel: 'dev-only',
      labelFormat: '[filename]--[local]',
    },
  },
```
기존 nextConfig에 명시되어 있던 emotion에 대한 compiler옵션이 위와 같이 되어 있음
dev환경에서 filename과 코드내에 선언된 StyledComponent명을 합쳐 css선택자의 format을 만들어주는 옵션인데 중요한건 이 filename,
증상으로 봤을때 Babel에서는 정말 딱 filename만 lable의 문자열로 제공함, 하지만 SWC는 filename.확장자 까지 같이 문자열로 제공하여 `.`이  CSS 선택자로 같이 들어가게됨

## 해결
1. Babel을 이용하여 트랜스파일링 해준다.
2. 원인에서 살펴본 옵션에서 autoLabel옵션을 'never`로 설정해준다. (무조건 해시값으로만 CSS 선택자 생성)

현재는 next버전을 올리며 SWC Minifier를 사용하는게 목적이었으니 2번 해결책 사용

**Comment by Baek2back** [comment]
https://github.com/vercel/next.js/issues/36362

해당 이슈도 Open 되어 있어 링크 걸어두겠습니다~
